version: '3.8'

services:
  nginx:
    image: bitnami/nginx:latest
    container_name: docker_nginx
    ports:
      - 8004:80
    volumes:
      - ./backend:/var/www
      - ./nginx/laravel_block.conf:/opt/bitnami/nginx/conf/server_blocks/laravel_block.conf
    depends_on:
      - backend
      - database

  database:
    image: postgres
    container_name: docker_postgresql
    volumes:
      - ./postgresql/backend:/var/lib/postgresql/data
    ports:
      - 5444:5432
    environment: 
      POSTGRES_DB: public
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
  # Application Service
  backend:
    container_name: docker_backend
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
